### ISSUE TITLE
Issue with installation of the gem

### ISSUE THREAD

**Issue by dinever** [primer/octicons_helper#1]
Thanks for creating `octicons_helper`!

When installing the latest release(v1.0.0) from RubyGems, Bundler raised this error message:

```
Resolving dependencies..........
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 4.2.6)

    octicons_helper was resolved to 1.0.0, which depends on
      rails (~> 3.2)
```

The gem [depends on rails (~> 3.2)](https://github.com/primer/octicons_helper/blob/4a9efdc6188917f3b7c6d45e7de8b980242de431/octicons_helper.gemspec#L17), but we are using rails 4+. 

Then I tried to install it directly from GitHub([the latest commit](https://github.com/primer/octicons_helper/tree/fa28cb06c67ce0a1974a9e3238483d79157503c2)), the problem was solved. So it would be great if we can create a release for the newest version to fix this issue.

**Comment by jonrohan** [comment]
Fixed with new release `2.0.0`
